In [ ]:
from datetime import date, timedelta
from IPython.display import display

import polars as pl
import numpy as np

from mars.analysis.profiler import MarsDataProfiler
from mars.feature.binner import MarsNativeBinner, MarsOptimalBinner
from mars.analysis.evaluator import MarsBinEvaluator
from mars.utils.logger import set_log_level

pl.Config.set_fmt_str_lengths(100)
set_log_level("WARNING")

In [ ]:
np.random.seed(2024)
N_MONTHS = 6        
N_SAMPLES = 20000     
BASE_DATE = date(2024, 1, 1)

data_parts = []

print(f"🛠️  正在生成 20 个特征的模拟数据 ({N_MONTHS} 个月 x {N_SAMPLES} 样本)...")

for i in range(N_MONTHS):
    curr_month = BASE_DATE + timedelta(days=31 * i)
    month_data = {
        "apply_date": [curr_month] * N_SAMPLES
    }
    
    # 初始 Logits 偏置
    # 设置为 -3.0，使基础坏账率保持在 4.7% 左右 (Sigmoid(-3) ≈ 0.047)
    total_logits = np.full(N_SAMPLES, -3.0) 
    
    # -------------------------------------------------
    # A组: [00-04] 稳定特征 (Stable)
    # -------------------------------------------------
    # 模拟信用评分、收入等级等强特征
    for k in range(5):
        feat_name = f"feat_stable_{k:02d}"
        raw_val = np.random.normal(0, 1, N_SAMPLES)
        
        # 降低系数 (0.3 ~ 0.5)，避免单特征 IV 爆炸
        coef = np.random.choice([0.3, -0.3, 0.5, -0.4])
        total_logits += coef * raw_val
        
        # 少量缺失 (1%)
        val_with_nan = raw_val.copy()
        mask_nan = np.random.rand(N_SAMPLES) < 0.01
        val_with_nan[mask_nan] = np.nan
        month_data[feat_name] = val_with_nan

    # -------------------------------------------------
    # B组: [05-09] 漂移特征 (Drift)
    # -------------------------------------------------
    # 模拟某些政策变动导致的客群偏移
    for k in range(5):
        feat_name = f"feat_drift_{k:02d}"
        
        # 漂移幅度温和一点：半年偏移 0.5 个标准差
        drift_amount = i * 0.1 
        raw_val = np.random.normal(loc=drift_amount, scale=1, size=N_SAMPLES)
        
        # 弱相关 (0.1)，即使漂移也不会导致 badrate 剧烈波动
        total_logits += 0.1 * raw_val 
        
        val_with_nan = raw_val.copy()
        val_with_nan[np.random.rand(N_SAMPLES) < 0.05] = np.nan
        month_data[feat_name] = val_with_nan

    # -------------------------------------------------
    # C组: [10-14] 缺失恶化特征 (MissInc)
    # -------------------------------------------------
    # 模拟三方数据接口不稳定性
    for k in range(5):
        feat_name = f"feat_miss_{k:02d}"
        raw_val = np.random.normal(0, 1, N_SAMPLES)
        
        # 这种特征通常还是有点用的
        total_logits += 0.2 * raw_val
        
        # 缺失率从 70% -> 95%
        miss_rate = 0.7 + (i * 0.05) 
        val_with_nan = raw_val.copy()
        val_with_nan[np.random.rand(N_SAMPLES) < miss_rate] = np.nan
        month_data[feat_name] = val_with_nan

    # -------------------------------------------------
    # D组: [15-19] 纯噪声特征 (Noise)
    # -------------------------------------------------
    for k in range(5):
        feat_name = f"feat_noise_{k:02d}"
        raw_val = np.random.normal(0, 2, N_SAMPLES)
        # 完全不加入 total_logits
        month_data[feat_name] = raw_val

    # -------------------------------------------------
    # 生成 Target
    # -------------------------------------------------
    # 增加随机噪声项，模拟模型无法解释的部分
    # scale=1.0 保证信噪比合理，坏账率不会非0即1
    total_logits += np.random.normal(0, 1.0, N_SAMPLES)
    
    probs = 1 / (1 + np.exp(-total_logits))
    target = (np.random.rand(N_SAMPLES) < probs).astype(int)
    
    month_data["target"] = target
    
    # 统计当月坏账率
    bad_rate = target.mean()
    print(f"  - Month {i+1}: Bad Rate = {bad_rate:.2%}")
    
    data_parts.append(pl.DataFrame(month_data))

# 合并
df_test: pl.DataFrame = pl.concat(data_parts)
df_test = df_test.with_columns(pl.col("apply_date").cast(pl.String))

print("-" * 50)
print(f"✅ 数据生成完毕! Shape: {df_test.shape}")
print(f"   全局坏账率: {df_test['target'].mean():.2%}")
print("-" * 50)

🛠️  正在生成 20 个特征的模拟数据 (6 个月 x 20000 样本)...
  - Month 1: Bad Rate = 8.95%
  - Month 2: Bad Rate = 9.46%
  - Month 3: Bad Rate = 9.83%
  - Month 4: Bad Rate = 10.03%
  - Month 5: Bad Rate = 10.49%
  - Month 6: Bad Rate = 10.72%
--------------------------------------------------
✅ 数据生成完毕! Shape: (120000, 22)
   全局坏账率: 9.91%
--------------------------------------------------

In [ ]:
df_test.head()

shape: (5, 22)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬────────┐
│ apply_date ┆ feat_stabl ┆ feat_stab ┆ feat_stab ┆ … ┆ feat_nois ┆ feat_nois ┆ feat_nois ┆ target │
│ ---        ┆ e_00       ┆ le_01     ┆ le_02     ┆   ┆ e_02      ┆ e_03      ┆ e_04      ┆ ---    │
│ str        ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ i32    │
│            ┆ f64        ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆        │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪════════╡
│ 2024-01-01 ┆ 1.668047   ┆ 0.001636  ┆ -0.369792 ┆ … ┆ 2.792012  ┆ 1.007653  ┆ -1.36604  ┆ 1      │
│ 2024-01-01 ┆ 0.737348   ┆ 0.43103   ┆ 0.704325  ┆ … ┆ -2.19845  ┆ -0.033999 ┆ 0.046231  ┆ 0      │
│ 2024-01-01 ┆ -0.201538  ┆ -0.269814 ┆ 0.293191  ┆ … ┆ 2.372679  ┆ 1.951594  ┆ 2.254981  ┆ 0      │
│ 2024-01-01 ┆ -0.150912  ┆ 0.107329  ┆ -1.788568 ┆ … ┆ -0.838905 ┆ 0.146901  ┆ -3.287832 ┆ 0      │
│ 2024-01-01 ┆ 0.916052   ┆ -0.0137   ┆ 0.071821  ┆ … ┆ -1.081754 ┆ -2.042914 ┆ -0.734279 ┆ 0      │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴────────┘

In [ ]:
df_test.describe()

shape: (9, 23)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ apply_dat ┆ feat_stab ┆ feat_stab ┆ … ┆ feat_nois ┆ feat_nois ┆ feat_nois ┆ target   │
│ ---       ┆ e         ┆ le_00     ┆ le_01     ┆   ┆ e_02      ┆ e_03      ┆ e_04      ┆ ---      │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ f64      │
│           ┆ str       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 120000    ┆ 120000.0  ┆ 120000.0  ┆ … ┆ 120000.0  ┆ 120000.0  ┆ 120000.0  ┆ 120000.0 │
│ null_coun ┆ 0         ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ NaN       ┆ NaN       ┆ … ┆ 0.001408  ┆ 0.002392  ┆ 0.002051  ┆ 0.099125 │
│ std       ┆ null      ┆ NaN       ┆ NaN       ┆ … ┆ 1.999741  ┆ 1.994784  ┆ 1.995384  ┆ 0.298831 │
│ min       ┆ 2024-01-0 ┆ -4.659177 ┆ -4.390396 ┆ … ┆ -8.633718 ┆ -8.501689 ┆ -8.904743 ┆ 0.0      │
│           ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ null      ┆ -0.668368 ┆ -0.665434 ┆ … ┆ -1.354274 ┆ -1.346748 ┆ -1.348042 ┆ 0.0      │
│ 50%       ┆ null      ┆ 0.012339  ┆ 0.008848  ┆ … ┆ 0.008547  ┆ 0.010019  ┆ 0.003375  ┆ 0.0      │
│ 75%       ┆ null      ┆ 0.701091  ┆ 0.693815  ┆ … ┆ 1.343728  ┆ 1.351203  ┆ 1.35264   ┆ 0.0      │
│ max       ┆ 2024-06-0 ┆ 4.402141  ┆ 4.688606  ┆ … ┆ 8.165473  ┆ 8.71499   ┆ 9.245517  ┆ 1.0      │
│           ┆ 4         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
features = [col for col in df_test.columns if col.startswith("feat_")]
len(features)

20

In [ ]:
test_profiler = MarsDataProfiler(
    df=df_test,
    features=features,
    exclude_features = None,
    include_dtypes = None,
    custom_missing_values = None,
    custom_special_values = None,
    overview_batch_size = 500,
    psi_batch_size = 50,
    psi_n_bins = 10,
    psi_bin_method = "quantile",
    psi_cv_ignore_threshold = 0.05,
    sample_frac = None,
    config = None
)

In [ ]:
test_profiler_report = test_profiler.generate_profile(
    profile_by="month",
    dt_col="apply_date",
    config_overrides={
        "dq_metrics": ["missing", "zeros", "top1"],
        "stat_metrics": ["mean", "std", "min", "max",]
    }
)
test_profiler_report

In [ ]:
test_profiler_report.show_overview()

In [ ]:
test_profiler_report.show_dq("missing", ascending=False)

In [ ]:
test_profiler_report.show_trend("mean")

In [ ]:
overview, dq_table, stat_table = test_profiler_report.get_profile_data()
display(overview.head(), dq_table["missing"].head())

shape: (5, 11)
┌─────────────┬─────────┬────────────┬────────────┬───┬──────────┬──────────┬───────────┬──────────┐
│ feature     ┆ dtype   ┆ distributi ┆ missing_ra ┆ … ┆ mean     ┆ std      ┆ min       ┆ max      │
│ ---         ┆ ---     ┆ on         ┆ te         ┆   ┆ ---      ┆ ---      ┆ ---       ┆ ---      │
│ str         ┆ str     ┆ ---        ┆ ---        ┆   ┆ f64      ┆ f64      ┆ f64       ┆ f64      │
│             ┆         ┆ str        ┆ f64        ┆   ┆          ┆          ┆           ┆          │
╞═════════════╪═════════╪════════════╪════════════╪═══╪══════════╪══════════╪═══════════╪══════════╡
│ feat_drift_ ┆ Float64 ┆ ▂▂▄█▆▃▂▂   ┆ 0.050125   ┆ … ┆ 0.242571 ┆ 1.01432  ┆ -3.914277 ┆ 4.970171 │
│ 00          ┆         ┆            ┆            ┆   ┆          ┆          ┆           ┆          │
│ feat_drift_ ┆ Float64 ┆ ▂▂▃▇█▄▂▂   ┆ 0.049892   ┆ … ┆ 0.249165 ┆ 1.016231 ┆ -4.287416 ┆ 4.465295 │
│ 01          ┆         ┆            ┆            ┆   ┆          ┆          ┆           ┆          │
│ feat_drift_ ┆ Float64 ┆ ▂▂▃▇█▄▂▂   ┆ 0.049008   ┆ … ┆ 0.248441 ┆ 1.014433 ┆ -4.170083 ┆ 4.50833  │
│ 02          ┆         ┆            ┆            ┆   ┆          ┆          ┆           ┆          │
│ feat_drift_ ┆ Float64 ┆ ▂▂▃▇█▄▂▂   ┆ 0.050133   ┆ … ┆ 0.249488 ┆ 1.011788 ┆ -4.036734 ┆ 4.350508 │
│ 03          ┆         ┆            ┆            ┆   ┆          ┆          ┆           ┆          │
│ feat_drift_ ┆ Float64 ┆ ▂▂▂▆█▄▂▂   ┆ 0.049983   ┆ … ┆ 0.252674 ┆ 1.012562 ┆ -4.782146 ┆ 4.745254 │
│ 04          ┆         ┆            ┆            ┆   ┆          ┆          ┆           ┆          │
└─────────────┴─────────┴────────────┴────────────┴───┴──────────┴──────────┴───────────┴──────────┘

shape: (5, 9)
┌────────────┬─────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ feature    ┆ dtype   ┆ 2024-01-01 ┆ 2024-02-0 ┆ … ┆ 2024-04-0 ┆ 2024-05-0 ┆ 2024-06-0 ┆ total    │
│ ---        ┆ ---     ┆ ---        ┆ 1         ┆   ┆ 1         ┆ 1         ┆ 1         ┆ ---      │
│ str        ┆ str     ┆ f64        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ f64      │
│            ┆         ┆            ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆          │
╞════════════╪═════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ feat_drift ┆ Float64 ┆ 0.04935    ┆ 0.05135   ┆ … ┆ 0.04845   ┆ 0.05225   ┆ 0.05155   ┆ 0.050125 │
│ _00        ┆         ┆            ┆           ┆   ┆           ┆           ┆           ┆          │
│ feat_drift ┆ Float64 ┆ 0.0494     ┆ 0.0501    ┆ … ┆ 0.05145   ┆ 0.04975   ┆ 0.0494    ┆ 0.049892 │
│ _01        ┆         ┆            ┆           ┆   ┆           ┆           ┆           ┆          │
│ feat_drift ┆ Float64 ┆ 0.04675    ┆ 0.04985   ┆ … ┆ 0.0516    ┆ 0.04985   ┆ 0.0458    ┆ 0.049008 │
│ _02        ┆         ┆            ┆           ┆   ┆           ┆           ┆           ┆          │
│ feat_drift ┆ Float64 ┆ 0.0491     ┆ 0.04695   ┆ … ┆ 0.0507    ┆ 0.05125   ┆ 0.05055   ┆ 0.050133 │
│ _03        ┆         ┆            ┆           ┆   ┆           ┆           ┆           ┆          │
│ feat_drift ┆ Float64 ┆ 0.0502     ┆ 0.04945   ┆ … ┆ 0.0503    ┆ 0.05135   ┆ 0.04935   ┆ 0.049983 │
│ _04        ┆         ┆            ┆           ┆   ┆           ┆           ┆           ┆          │
└────────────┴─────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
(
    overview
    .filter(pl.col("missing_rate") < 0.8)
    .select("feature")
    .to_series()
    .to_list()
)

['feat_drift_00',
 'feat_drift_01',
 'feat_drift_02',
 'feat_drift_03',
 'feat_drift_04',
 'feat_noise_00',
 'feat_noise_01',
 'feat_noise_02',
 'feat_noise_03',
 'feat_noise_04',
 'feat_stable_00',
 'feat_stable_01',
 'feat_stable_02',
 'feat_stable_03',
 'feat_stable_04']

In [ ]:
test_native_binner = MarsNativeBinner(
    features=features,
    method = "quantile",
    n_bins = 10,
    special_values = None,
    missing_values = None,
    min_samples = 0.05, # 仅对 cart 有效
    cart_params = None,
    remove_empty_bins = False, # 仅对 uniform 有效
    n_jobs = -1
)
test_native_binner.fit(df_test, df_test["target"])

MarsNativeBinner(features=['feat_stable_00', 'feat_stable_01', 'feat_stable_02',
                           'feat_stable_03', 'feat_stable_04', 'feat_drift_00',
                           'feat_drift_01', 'feat_drift_02', 'feat_drift_03',
                           'feat_drift_04', 'feat_miss_00', 'feat_miss_01',
                           'feat_miss_02', 'feat_miss_03', 'feat_miss_04',
                           'feat_noise_00', 'feat_noise_01', 'feat_noise_02',
                           'feat_noise_03', 'feat_noise_04'],
                 missing_values=[], n_jobs=23, special_values=[])

In [ ]:
trans_cols = ["feat_stable_00", "feat_drift_00", "feat_miss_00", "feat_noise_00"]
display(test_native_binner.transform(df_test[trans_cols], return_type ="label", lazy=True).collect().head(5))
# display(test_native_binner.transform(df_test[trans_cols], return_type ="index").head(5))
display(test_native_binner.transform(df_test[trans_cols], return_type ="woe").head(5))

shape: (5, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ feat_stabl ┆ feat_drift ┆ feat_miss_ ┆ feat_nois ┆ feat_stab ┆ feat_nois ┆ feat_drif ┆ feat_miss │
│ e_00       ┆ _00        ┆ 00         ┆ e_00      ┆ le_00_bin ┆ e_00_bin  ┆ t_00_bin  ┆ _00_bin   │
│ ---        ┆ ---        ┆ ---        ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ f64        ┆ f64        ┆ f64        ┆ f64       ┆ str       ┆ str       ┆ str       ┆ str       │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1.668047   ┆ 0.558442   ┆ NaN        ┆ -2.046308 ┆ 09_[1.29, ┆ 01_[-2.55 ┆ 06_[0.5,  ┆ Missing   │
│            ┆            ┆            ┆           ┆ inf)      ┆ , -1.68)  ┆ 0.778)    ┆           │
│ 0.737348   ┆ 1.272808   ┆ NaN        ┆ 0.437779  ┆ 07_[0.526 ┆ 05_[0.000 ┆ 08_[1.1,  ┆ Missing   │
│            ┆            ┆            ┆           ┆ , 0.842)  ┆ 281,      ┆ 1.54)     ┆           │
│            ┆            ┆            ┆           ┆           ┆ 0.51)     ┆           ┆           │
│ -0.201538  ┆ -1.66749   ┆ -0.850332  ┆ 2.524236  ┆ 04_[-0.25 ┆ 08_[1.68, ┆ 00_[-inf, ┆ 02_[-0.85 │
│            ┆            ┆            ┆           ┆ 5,        ┆ 2.55)     ┆ -1.05)    ┆ 4,        │
│            ┆            ┆            ┆           ┆ 0.0005)   ┆           ┆           ┆ -0.534)   │
│ -0.150912  ┆ -0.911884  ┆ -0.200391  ┆ 1.337186  ┆ 04_[-0.25 ┆ 07_[1.05, ┆ 01_[-1.05 ┆ 04_[-0.25 │
│            ┆            ┆            ┆           ┆ 5,        ┆ 1.68)     ┆ , -0.615) ┆ 2,        │
│            ┆            ┆            ┆           ┆ 0.0005)   ┆           ┆           ┆ 0.000196) │
│ 0.916052   ┆ -0.145678  ┆ -0.302291  ┆ 1.685961  ┆ 08_[0.842 ┆ 08_[1.68, ┆ 03_[-0.29 ┆ 03_[-0.53 │
│            ┆            ┆            ┆           ┆ , 1.29)   ┆ 2.55)     ┆ 3,        ┆ 4,        │
│            ┆            ┆            ┆           ┆           ┆           ┆ -0.0174)  ┆ -0.252)   │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

shape: (5, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ feat_stabl ┆ feat_drift ┆ feat_miss_ ┆ feat_nois ┆ feat_stab ┆ feat_nois ┆ feat_drif ┆ feat_miss │
│ e_00       ┆ _00        ┆ 00         ┆ e_00      ┆ le_00_woe ┆ e_00_woe  ┆ t_00_woe  ┆ _00_woe   │
│ ---        ┆ ---        ┆ ---        ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ f64        ┆ f64        ┆ f64        ┆ f64       ┆ f32       ┆ f32       ┆ f32       ┆ f32       │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1.668047   ┆ 0.558442   ┆ NaN        ┆ -2.046308 ┆ 0.087631  ┆ 0.026317  ┆ 0.000073  ┆ 0.009086  │
│ 0.737348   ┆ 1.272808   ┆ NaN        ┆ 0.437779  ┆ -0.004348 ┆ 0.04275   ┆ 0.151691  ┆ 0.009086  │
│ -0.201538  ┆ -1.66749   ┆ -0.850332  ┆ 2.524236  ┆ -0.001514 ┆ -0.093493 ┆ -0.155635 ┆ -0.163249 │
│ -0.150912  ┆ -0.911884  ┆ -0.200391  ┆ 1.337186  ┆ -0.001514 ┆ -0.024026 ┆ -0.102276 ┆ -0.10398  │
│ 0.916052   ┆ -0.145678  ┆ -0.302291  ┆ 1.685961  ┆ -0.00057  ┆ -0.093493 ┆ -0.042901 ┆ -0.133252 │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

In [ ]:
test_native_bin_performance_table = test_native_binner.profile_bin_performance(df_test[features], df_test["target"], update_woe=True)

In [ ]:
trans_cols = ["feat_stable_00", "feat_drift_00", "feat_miss_00", "feat_noise_00"]
display(test_native_binner.transform(df_test[trans_cols], return_type ="label", lazy=True).collect().head(5))
# display(test_native_binner.transform(df_test[trans_cols], return_type ="index").head(5))
display(test_native_binner.transform(df_test[trans_cols], return_type ="woe").head(5))

shape: (5, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ feat_stabl ┆ feat_drift ┆ feat_miss_ ┆ feat_nois ┆ feat_stab ┆ feat_nois ┆ feat_drif ┆ feat_miss │
│ e_00       ┆ _00        ┆ 00         ┆ e_00      ┆ le_00_bin ┆ e_00_bin  ┆ t_00_bin  ┆ _00_bin   │
│ ---        ┆ ---        ┆ ---        ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ f64        ┆ f64        ┆ f64        ┆ f64       ┆ str       ┆ str       ┆ str       ┆ str       │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1.668047   ┆ 0.558442   ┆ NaN        ┆ -2.046308 ┆ 09_[1.29, ┆ 01_[-2.55 ┆ 06_[0.5,  ┆ Missing   │
│            ┆            ┆            ┆           ┆ inf)      ┆ , -1.68)  ┆ 0.778)    ┆           │
│ 0.737348   ┆ 1.272808   ┆ NaN        ┆ 0.437779  ┆ 07_[0.526 ┆ 05_[0.000 ┆ 08_[1.1,  ┆ Missing   │
│            ┆            ┆            ┆           ┆ , 0.842)  ┆ 281,      ┆ 1.54)     ┆           │
│            ┆            ┆            ┆           ┆           ┆ 0.51)     ┆           ┆           │
│ -0.201538  ┆ -1.66749   ┆ -0.850332  ┆ 2.524236  ┆ 04_[-0.25 ┆ 08_[1.68, ┆ 00_[-inf, ┆ 02_[-0.85 │
│            ┆            ┆            ┆           ┆ 5,        ┆ 2.55)     ┆ -1.05)    ┆ 4,        │
│            ┆            ┆            ┆           ┆ 0.0005)   ┆           ┆           ┆ -0.534)   │
│ -0.150912  ┆ -0.911884  ┆ -0.200391  ┆ 1.337186  ┆ 04_[-0.25 ┆ 07_[1.05, ┆ 01_[-1.05 ┆ 04_[-0.25 │
│            ┆            ┆            ┆           ┆ 5,        ┆ 1.68)     ┆ , -0.615) ┆ 2,        │
│            ┆            ┆            ┆           ┆ 0.0005)   ┆           ┆           ┆ 0.000196) │
│ 0.916052   ┆ -0.145678  ┆ -0.302291  ┆ 1.685961  ┆ 08_[0.842 ┆ 08_[1.68, ┆ 03_[-0.29 ┆ 03_[-0.53 │
│            ┆            ┆            ┆           ┆ , 1.29)   ┆ 2.55)     ┆ 3,        ┆ 4,        │
│            ┆            ┆            ┆           ┆           ┆           ┆ -0.0174)  ┆ -0.252)   │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

shape: (5, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ feat_stabl ┆ feat_drift ┆ feat_miss_ ┆ feat_nois ┆ feat_stab ┆ feat_nois ┆ feat_drif ┆ feat_miss │
│ e_00       ┆ _00        ┆ 00         ┆ e_00      ┆ le_00_woe ┆ e_00_woe  ┆ t_00_woe  ┆ _00_woe   │
│ ---        ┆ ---        ┆ ---        ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ f64        ┆ f64        ┆ f64        ┆ f64       ┆ f32       ┆ f32       ┆ f32       ┆ f32       │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1.668047   ┆ 0.558442   ┆ NaN        ┆ -2.046308 ┆ 0.087631  ┆ 0.026317  ┆ 0.000073  ┆ 0.009086  │
│ 0.737348   ┆ 1.272808   ┆ NaN        ┆ 0.437779  ┆ -0.004348 ┆ 0.04275   ┆ 0.151691  ┆ 0.009086  │
│ -0.201538  ┆ -1.66749   ┆ -0.850332  ┆ 2.524236  ┆ -0.001514 ┆ -0.093493 ┆ -0.155635 ┆ -0.163249 │
│ -0.150912  ┆ -0.911884  ┆ -0.200391  ┆ 1.337186  ┆ -0.001514 ┆ -0.024026 ┆ -0.102276 ┆ -0.10398  │
│ 0.916052   ┆ -0.145678  ┆ -0.302291  ┆ 1.685961  ┆ -0.00057  ┆ -0.093493 ┆ -0.042901 ┆ -0.133252 │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

In [ ]:
test_opt_biner = MarsOptimalBinner(
    features=features,
    cat_features = None,
    n_bins = 10,
    min_n_bins = 2,
    min_bin_size = 0.02,
    n_prebins = 20,
    prebinning_method = "cart",
    min_prebin_size = 0.01,
    monotonic_trend = "auto_asc_desc",
    solver = "cp",
    time_limit = 2,
    special_values = None,
    missing_values = None,
    cart_params = {"random_state": 2025},
    n_jobs = -1
)
test_opt_biner.fit(df_test, df_test["target"])

In [ ]:
test_opt_biner.fit_failures_

In [ ]:
trans_cols = ["feat_stable_00", "feat_drift_00", "feat_miss_00", "feat_noise_00"]
display(test_opt_biner.transform(df_test[trans_cols], return_type ="label", lazy=True).collect().head(3))
display(test_opt_biner.transform(df_test[trans_cols], return_type ="index").head(3))
display(test_opt_biner.transform(df_test[trans_cols], return_type ="woe").head(3))

In [ ]:
test_opt_bin_performance_table = test_opt_biner.profile_bin_performance(df_test[features], df_test["target"])
test_opt_bin_performance_table

In [ ]:
test_evaluator = MarsBinEvaluator(binner=test_native_binner, target_col="target")

test_evaluator_report = test_evaluator.evaluate(
    df=df_test,
    features=features,
    profile_by="month",
    dt_col="apply_date"
)

In [ ]:
test_evaluator_report

In [ ]:
display(test_evaluator_report.show_trend("psi", ascending=False))

In [ ]:
display(test_evaluator_report.show_trend("iv", ascending=True))

In [ ]:
display(test_evaluator_report.show_trend("risk_corr", ascending=False))

In [ ]:
summary_df, trend_tables, detail_table = test_evaluator_report.get_evaluation_data()

In [ ]:
trend_tables["auc"]

In [ ]:
detail_table

In [ ]:
test_evaluator_report.write_excel()

In [ ]:
test_evaluator.plot_feature_binning_risk_trends(
    test_evaluator_report,
    sort_by="iv",
    dpi=144
)